steps:
  # Step 1: Build (same as CodeBuild)
  - name: 'node:20'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Installing dependencies..."
        npm install --legacy-peer-deps
        echo "Building Medusa..."
        npx medusa build

  # Step 2: SSH into Compute Engine and deploy (same as CodeDeploy)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Connecting to Compute Engine..."
        gcloud compute ssh ubuntu@medusa --zone=us-east4-a --command="
          cd /home/ubuntu/medusa-server/medusa_ecommerce_store-1 &&
          git pull origin master &&
          chmod +x scripts/*.sh &&
          ./scripts/AfterInstall.sh &&
          ./scripts/Applicationstart.sh
        "

artifacts:
  objects:
    location: gs://medusa-demo/
    paths: ['**/*']

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
